function klu_make
%KLU_MAKE compiles the KLU mexFunctions
%
% Example:
%   klu_make
%
% KLU relies on AMD, COLAMD, and BTF for its ordering options, and can
% optionally use CHOLMOD, CCOLAMD, CAMD, and METIS as well.
%
% You must type the klu_make command while in the KLU/MATLAB directory.
%
% See also klu.

% KLU, Copyright (c) 2004-2022, University of Florida.  All Rights Reserved.
% Authors: Timothy A. Davis and Ekanathan Palamadai.
% SPDX-License-Identifier: LGPL-2.1+

metis_path = getenv ('METIS_ROOT') ;
with_cholmod = ~isempty (metis_path) ;

details = 0 ;       % if 1, print details of each command

d = '' ;
if (~isempty (strfind (computer, '64')))
    % 64-bit MATLAB
    d = '-largeArrayDims' ;
end

% MATLAB 8.3.0 now has a -silent option to keep 'mex' from burbling too much
if (~verLessThan ('matlab', '8.3.0'))
    d = ['-silent ' d] ;
end

if (ispc)
    % MSVC does not define ssize_t
    d = [d ' -DNO_SSIZE_T'] ;
    % disable the SuiteSparse_config timer
    d = ['-DNTIMER ' d] ;
end

fprintf ('Compiling KLU ') ;
kk = 0 ; 

include = '-I. -I../../AMD/Include -I../../COLAMD/Include -I../Include -I../../SuiteSparse_config -I../../BTF/Include' ;

if (with_cholmod)
    fprintf ('with CHOLMOD, CAMD, CCOLAMD, and METIS\n') ;
    include = [include ' -I../../CCOLAMD/Include -I../../CAMD/Include -I../../CHOLMOD/Include -I../User -I../../CHOLMOD'] ;
    include = [include ' -I' metis_path '/include'] ;
    include = ['-DNSUPERNODAL -DNMODIFY -DNMATRIXOPS -DNCHECK ' include] ;
else
    fprintf ('without CHOLMOD, CAMD, CCOLAMD, and METIS\n') ;
    include = ['-DNCHOLMOD ' include] ;
end

% do not attempt to compile CHOLMOD with large file support (not needed)
include = [include ' -DNLARGEFILE'] ;

suitesparse_src = { '../../SuiteSparse_config/SuiteSparse_config' } ;

amd_src = { ...
    '../../AMD/Source/amd_1', ...
    '../../AMD/Source/amd_2', ...
    '../../AMD/Source/amd_aat', ...
    '../../AMD/Source/amd_control', ...
    '../../AMD/Source/amd_defaults', ...
    '../../AMD/Source/amd_dump', ...
    '../../AMD/Source/amd_info', ...
    '../../AMD/Source/amd_order', ...
    '../../AMD/Source/amd_postorder', ...
    '../../AMD/Source/amd_post_tree', ...
    '../../AMD/Source/amd_preprocess', ...
    '../../AMD/Source/amd_valid' } ;

colamd_src = {
    '../../COLAMD/Source/colamd' } ;

if (with_cholmod)

    camd_src = { ...
        '../../CAMD/Source/camd_1', ...
        '../../CAMD/Source/camd_2', ...
        '../../CAMD/Source/camd_aat', ...
        '../../CAMD/Source/camd_control', ...
        '../../CAMD/Source/camd_defaults', ...
        '../../CAMD/Source/camd_dump', ...
        '../../CAMD/Source/camd_info', ...
        '../../CAMD/Source/camd_order', ...
        '../../CAMD/Source/camd_postorder', ...
        '../../CAMD/Source/camd_preprocess', ...
        '../../CAMD/Source/camd_valid' } ;

    ccolamd_src = {
        '../../CCOLAMD/Source/ccolamd' } ;

    cholmod_src = {
        '../../CHOLMOD/Utility/t_cholmod_aat', ...
        '../../CHOLMOD/Utility/t_cholmod_add', ...
        '../../CHOLMOD/Utility/t_cholmod_add_size_t', ...
        '../../CHOLMOD/Utility/t_cholmod_allocate_dense', ...
        '../../CHOLMOD/Utility/cholmod_allocate_factor', ...
        '../../CHOLMOD/Utility/t_cholmod_allocate_sparse', ...
        '../../CHOLMOD/Utility/t_cholmod_allocate_triplet', ...
        '../../CHOLMOD/Utility/cholmod_allocate_work', ...
        '../../CHOLMOD/Utility/t_cholmod_alloc_factor', ...
        '../../CHOLMOD/Utility/t_cholmod_alloc_work', ...
        '../../CHOLMOD/Utility/t_cholmod_band', ...
        '../../CHOLMOD/Utility/t_cholmod_band_nnz', ...
        '../../CHOLMOD/Utility/t_cholmod_malloc', ...
        '../../CHOLMOD/Utility/t_cholmod_change_factor', ...
        '../../CHOLMOD/Utility/t_cholmod_clear_flag', ...
        '../../CHOLMOD/Utility/t_cholmod_copy', ...
        '../../CHOLMOD/Utility/t_cholmod_copy_dense2', ...
        '../../CHOLMOD/Utility/t_cholmod_copy_dense', ...
        '../../CHOLMOD/Utility/t_cholmod_copy_factor', ...
        '../../CHOLMOD/Utility/t_cholmod_copy_sparse', ...
        '../../CHOLMOD/Utility/t_cholmod_copy_triplet', ...
        '../../CHOLMOD/Utility/t_cholmod_cumsum', ...
        '../../CHOLMOD/Utility/t_cholmod_bound', ...
        '../../CHOLMOD/Utility/t_cholmod_defaults', ...
        '../../CHOLMOD/Utility/t_cholmod_dense_nnz', ...
        '../../CHOLMOD/Utility/t_cholmod_dense_to_sparse', ...
        '../../CHOLMOD/Utility/cholmod_divcomplex', ...
        '../../CHOLMOD/Utility/t_cholmod_ensure_dense', ...
        '../../CHOLMOD/Utility/t_cholmod_error', ...
        '../../CHOLMOD/Utility/t_cholmod_eye', ...
        '../../CHOLMOD/Utility/t_cholmod_factor_to_sparse', ...
        '../../CHOLMOD/Utility/t_cholmod_finish', ...
        '../../CHOLMOD/Utility/t_cholmod_free', ...
        '../../CHOLMOD/Utility/t_cholmod_free_dense', ...
        '../../CHOLMOD/Utility/t_cholmod_free_factor', ...
        '../../CHOLMOD/Utility/t_cholmod_free_sparse', ...
        '../../CHOLMOD/Utility/t_cholmod_free_triplet', ...
        '../../CHOLMOD/Utility/t_cholmod_free_work', ...
        '../../CHOLMOD/Utility/cholmod_hypot', ...
        '../../CHOLMOD/Utility/t_cholmod_malloc', ...
        '../../CHOLMOD/Utility/t_cholmod_maxrank', ...
        '../../CHOLMOD/Utility/t_cholmod_mult_size_t', ...
        '../../CHOLMOD/Utility/t_cholmod_nnz', ...
        '../../CHOLMOD/Utility/t_cholmod_ones', ...
        '../../CHOLMOD/Utility/t_cholmod_pack_factor', ...
        '../../CHOLMOD/Utility/t_cholmod_ptranspose', ...
        '../../CHOLMOD/Utility/t_cholmod_reallocate_column', ...
        '../../CHOLMOD/Utility/t_cholmod_reallocate_factor', ...
        '../../CHOLMOD/Utility/t_cholmod_reallocate_sparse', ...
        '../../CHOLMOD/Utility/t_cholmod_reallocate_triplet', ...
        '../../CHOLMOD/Utility/t_cholmod_realloc', ...
        '../../CHOLMOD/Utility/t_cholmod_realloc_multiple', ...
        '../../CHOLMOD/Utility/t_cholmod_bound', ...
        '../../CHOLMOD/Utility/t_cholmod_score_comp', ...
        '../../CHOLMOD/Utility/t_cholmod_set_empty', ...
        '../../CHOLMOD/Utility/t_cholmod_sort', ...
        '../../CHOLMOD/Utility/t_cholmod_sparse_to_dense', ...
        '../../CHOLMOD/Utility/t_cholmod_sparse_to_triplet', ...
        '../../CHOLMOD/Utility/t_cholmod_speye', ...
        '../../CHOLMOD/Utility/t_cholmod_spzeros', ...
        '../../CHOLMOD/Utility/t_cholmod_start', ...
        '../../CHOLMOD/Utility/t_cholmod_transpose', ...
        '../../CHOLMOD/Utility/t_cholmod_transpose_sym', ...
        '../../CHOLMOD/Utility/t_cholmod_transpose_unsym', ...
        '../../CHOLMOD/Utility/t_cholmod_triplet_to_sparse', ...
        '../../CHOLMOD/Utility/t_cholmod_version', ...
        '../../CHOLMOD/Utility/t_cholmod_change_xdtype', ...
        '../../CHOLMOD/Utility/t_cholmod_zeros', ...
        '../../CHOLMOD/Utility/cholmod_mult_uint64_t', ...
        '../../CHOLMOD/Utility/cholmod_memdebug', ...
        '../../CHOLMOD/Check/cholmod_check', ...
        '../../CHOLMOD/Cholesky/cholmod_amd', ...
        '../../CHOLMOD/Cholesky/cholmod_analyze', ...
        '../../CHOLMOD/Cholesky/cholmod_colamd', ...
        '../../CHOLMOD/Cholesky/cholmod_etree', ...
        '../../CHOLMOD/Cholesky/cholmod_postorder', ...
        '../../CHOLMOD/Cholesky/cholmod_rowcolcounts', ...
        '../../CHOLMOD/Partition/cholmod_ccolamd', ...
        '../../CHOLMOD/Partition/cholmod_csymamd', ...
        '../../CHOLMOD/Partition/cholmod_camd', ...
        '../../CHOLMOD/Partition/cholmod_metis', ...
        '../../CHOLMOD/Partition/cholmod_nesdis' } ;

else
    camd_src = { } ;
    ccolamd_src = { } ;
    cholmod_src = { } ;
end

btf_src = {
    '../../BTF/Source/btf_maxtrans', ...
    '../../BTF/Source/btf_order', ...
    '../../BTF/Source/btf_strongcomp' } ;

klu_src = {
    '../Source/klu_free_symbolic', ...
    '../Source/klu_defaults', ...
    '../Source/klu_analyze_given', ...
    '../Source/klu_analyze', ...
    '../Source/klu_memory' } ;

if (with_cholmod)
    klu_src = [klu_src { '../User/klu_cholmod' }] ;                       %#ok
end

klu_zlsrc = {
    '../Source/klu', ...
    '../Source/klu_kernel', ...
    '../Source/klu_dump', ...
    '../Source/klu_factor', ...
    '../Source/klu_free_numeric', ...
    '../Source/klu_solve', ...
    '../Source/klu_scale', ...
    '../Source/klu_refactor', ...
    '../Source/klu_tsolve', ...
    '../Source/klu_diagnostics', ...
    '../Source/klu_sort', ...
    '../Source/klu_extract', ...
    } ;

klu_lsrc = {
    '../Source/klu', ...
    '../Source/klu_kernel', ...
    '../Source/klu_dump', ...
    '../Source/klu_factor', ...
    '../Source/klu_free_numeric', ...
    '../Source/klu_solve', ...
    '../Source/klu_scale', ...
    '../Source/klu_refactor', ...
    '../Source/klu_tsolve', ...
    '../Source/klu_diagnostics', ...
    '../Source/klu_sort', ...
    '../Source/klu_extract', ...
    } ;

try
    % ispc does not appear in MATLAB 5.3
    pc = ispc ;
catch
    % if ispc fails, assume we are on a Windows PC if it's not unix
    pc = ~isunix ;
end

if (pc)
    obj_extension = '.obj' ;
else
    obj_extension = '.o' ;
end

% compile each library source file
obj = ' ' ;

source = [suitesparse_src amd_src btf_src klu_src colamd_src] ;
if (with_cholmod)
    source = [ccolamd_src camd_src cholmod_src source] ;
end
source = [source klu_zlsrc] ;
source = [source klu_lsrc] ;

for f = source
    ff = f {1} ;
    slash = strfind (ff, '/') ;
    if (isempty (slash))
        slash = 1 ;
    else
        slash = slash (end) + 1 ;
    end
    o = ff (slash:end) ;
    % fprintf ('%s\n', o) ;
    variant_flags = '' ;
    variant_suffix = '' ;
    if (ismember (ff, klu_zlsrc))
        variant_flags = '-DCOMPLEX -DDLONG' ;
        variant_suffix = '_zl' ;
    elseif (ismember (ff, klu_lsrc))
        variant_flags = '-DDLONG' ;
        variant_suffix = '_l' ;
    end
    o = [o variant_suffix obj_extension] ;
    obj = [obj  ' ' o] ;					            %#ok
    s = sprintf ('mex %s -O %s %s -c %s.c', d, variant_flags, include, ff) ;
    kk = do_cmd (s, kk, details) ;
end

% compile the KLU mexFunction
s = sprintf ('mex %s -O %s -output klu klu_mex.c', d, include) ;
s = [s obj] ;                                                               %#ok

if (~(ispc || ismac))
    % for POSIX timing routine
    s = [s ' -lrt'] ;
end

kk = do_cmd (s, kk, details) ;

% clean up
s = ['delete ' obj] ;
do_cmd (s, kk, details) ;

fprintf ('\nKLU successfully compiled\n') ;

%-------------------------------------------------------------------------------

function rmfile (file)
% rmfile:  delete a file, but only if it exists
if (length (dir (file)) > 0)                                                %#ok
    delete (file) ;
end

%-------------------------------------------------------------------------------
function kk = do_cmd (s, kk, details)
%DO_CMD: evaluate a command, and either print it or print a "."
if (details)
    fprintf ('%s\n', s) ;
else
    if (mod (kk, 60) == 0)
        fprintf ('\n') ;
    end
    kk = kk + 1 ;
    fprintf ('.') ;
end
eval (s) ;

