#!/bin/bash

# Fresh build of SuperLU_MT 4.0.1 with icx and OpenMP

rm -rf build/*
cd build
export MKL_THREADING_LAYER=GNU
CC=gcc CXX=g++ cmake -DPLAT=_OPENMP -DBLA_VENDOR=Intel10_64lp -DMKL_ROOT=/sw/eb/sw/imkl/2024.2.0/mkl/2024.2/  -DMKL_GCC_HACK=ON ..
# cmake -LA . | grep -v NOTFOUND
cmake --build . --config Release
ldd EXAMPLE/pdlinsolx_paru
