function paru_make (try_intel)
%PARU_MAKE compiles the ParU mexFunction
%
% Usage: paru_make
%
% Example:
%
%   paru_make
%   load west0479
%   A = west0479 ;
%   n = size (A,1) ;
%   b = rand (n,1) ;
%   x1 = A\b ;
%   norm (A*x1-b)
%   x2 = paru (A,b) ;
%   norm (A*x2-b)
%
% You must type the paru_make command while in the ParU/MATLAB directory.
%
% For best performance, paru relies on functions unique to the Intel MKL BLAS.
% An optional input, paru_make(try_intel), is true by default.  paru_make
% detects the BLAS library used by MATLAB and then attempts to use functions
% unique to the Intel MKL BLAS library (mkl*set_num_threads_local).  This may
% fail when paru is compiled (in which case paru is compiled with try_intel
% false).  If paru fails when it runs, with a link error reporting that an an
% mkl_* routine is not found, use paru_make(false) to disable the Intel MKL
% functions.
%
% See also paru, paru_demo, paru_many, paru_tiny, mldivide.

% ParU, Copyright (c) 2022-2025, Mohsen Aznaveh and Timothy A. Davis,
% All Rights Reserved.
% SPDX-License-Identifier: GPL-3.0-or-later

if (nargin < 1)
    try_intel = (~ismac && isunix) ;
end
if (try_intel)
    v = version ('-blas') ;
    try_intel = contains (v, 'Intel') ;
end
if (try_intel)
    try
        paru_make_helper (true) ;
    catch
        fprintf ('\nCompilation with Intel MKL specific methods failed.\n') ;
        fprintf ('Retrying with standard BLAS API.\n') ;
        paru_make_helper (false) ;
    end
else
    paru_make_helper (false) ;
end
end

%-------------------------------------------------------------------------------

function paru_make_helper (try_intel)
fprintf ('Compiling ParU for MATLAB.\n') ;
if (try_intel)
    fprintf ('Using the Intel MKL BLAS\n') ;
end

% -R2018a: interleaved complex is required
flags = '-O -R2018a -silent ' ;

% developer-only flag, for testing only, not intended for end users:
flags = [flags ' -DDEVELOPER=1 ' ] ;

if (ispc)
    % MSVC does not define ssize_t
    flags = [flags ' -DNO_SSIZE_T -DNTIMER -DBLAS_NO_UNDERSCORE '] ;
end

if (ismac)
    flags = [flags ' -DCLANG_NEEDS_MAIN'] ;
end

libs = '-lmwlapack -lmwblas' ;
if (~(ispc || ismac))
    % for POSIX timing routine
    libs = [libs ' -lrt'] ;
end

openmp = '' ;
if (~ismac && isunix)
    openmp = ' -fopenmp' ;
end
flags = sprintf ('%s CFLAGS=''-fPIC %s'' LDFLAGS=''%s''', flags, openmp, openmp) ;

if (ispc)
    obj = 'obj' ;
else
    obj = 'o' ;
end

% check if MATLAB has the MKL Intel BLAS on Linux or Mac
if (try_intel && (ismac || isunix))
    v = version ('-blas') ;
    if (contains (v, 'Intel'))
        flags = [flags ' -DBLAS_Intel10_64ilp -DBLAS_Intel10'] ;
    end
end

% use all of CHOLMOD except for the Modify module
flags = [flags ' -DNMODIFY -DBLAS64 -DNPARTITION' ] ;
if (ispc)
    % MSVC does not define ssize_t
    flags = [flags ' -DNO_SSIZE_T'] ;
end

%-------------------------------------------------------------------------------

include = '-I../../include -I../Include' ;
include = [include ' -I../../SuiteSparse_config '] ;
include = [include ' -I../../AMD/Source  -I../../AMD/Include  '] ;
include = [include ' -I../../CAMD/Source -I../../CAMD/Include '] ;
include = [include ' -I../../COLAMD/Source  -I../../COLAMD/Include  '] ;
include = [include ' -I../../CCOLAMD/Source -I../../CCOLAMD/Include '] ;
include = [include ' -I../../UMFPACK/Source -I../../UMFPACK/Include '] ;
include = [include ' -I../../CHOLMOD/Include '] ;
include = [include ' -I../../CHOLMOD/Check '] ;
include = [include ' -I../../CHOLMOD/Cholesky '] ;
include = [include ' -I../../CHOLMOD/Utility '] ;
include = [include ' -I../../CHOLMOD/MATLAB '] ;
include = [include ' -I../../CHOLMOD/MatrixOps '] ;
include = [include ' -I../../CHOLMOD/Partition '] ;
include = [include ' -I../../CHOLMOD '] ;
include = [include ' -I../../CHOLMOD/Supernodal '] ;

suitesparse_src = { ...
    '../../SuiteSparse_config/SuiteSparse_config', ...
    '../../AMD/Source/amd_1', ...
    '../../AMD/Source/amd_2', ...
    '../../AMD/Source/amd_aat', ...
    '../../AMD/Source/amd_control', ...
    '../../AMD/Source/amd_defaults', ...
    '../../AMD/Source/amd_dump', ...
    '../../AMD/Source/amd_info', ...
    '../../AMD/Source/amd_order', ...
    '../../AMD/Source/amd_postorder', ...
    '../../AMD/Source/amd_post_tree', ...
    '../../AMD/Source/amd_preprocess', ...
    '../../AMD/Source/amd_valid', ...
    '../../CAMD/Source/camd_1', ...
    '../../CAMD/Source/camd_2', ...
    '../../CAMD/Source/camd_aat', ...
    '../../CAMD/Source/camd_control', ...
    '../../CAMD/Source/camd_defaults', ...
    '../../CAMD/Source/camd_dump', ...
    '../../CAMD/Source/camd_info', ...
    '../../CAMD/Source/camd_order', ...
    '../../CAMD/Source/camd_postorder', ...
    '../../CAMD/Source/camd_preprocess', ...
    '../../CAMD/Source/camd_valid', ...
    '../../COLAMD/Source/colamd', ...
    '../../CCOLAMD/Source/ccolamd', ...
    '../../CHOLMOD/MATLAB/sputil2', ...
    '../../CHOLMOD/Utility/t_cholmod_aat', ...
    '../../CHOLMOD/Utility/t_cholmod_add', ...
    '../../CHOLMOD/Utility/t_cholmod_add_size_t', ...
    '../../CHOLMOD/Utility/t_cholmod_allocate_dense', ...
    '../../CHOLMOD/Utility/cholmod_allocate_factor', ...
    '../../CHOLMOD/Utility/t_cholmod_allocate_sparse', ...
    '../../CHOLMOD/Utility/t_cholmod_allocate_triplet', ...
    '../../CHOLMOD/Utility/cholmod_allocate_work', ...
    '../../CHOLMOD/Utility/t_cholmod_alloc_factor', ...
    '../../CHOLMOD/Utility/t_cholmod_alloc_work', ...
    '../../CHOLMOD/Utility/t_cholmod_band', ...
    '../../CHOLMOD/Utility/t_cholmod_band_nnz', ...
    '../../CHOLMOD/Utility/t_cholmod_malloc', ...
    '../../CHOLMOD/Utility/t_cholmod_change_factor', ...
    '../../CHOLMOD/Utility/t_cholmod_clear_flag', ...
    '../../CHOLMOD/Utility/t_cholmod_copy', ...
    '../../CHOLMOD/Utility/t_cholmod_copy_dense2', ...
    '../../CHOLMOD/Utility/t_cholmod_copy_dense', ...
    '../../CHOLMOD/Utility/t_cholmod_copy_factor', ...
    '../../CHOLMOD/Utility/t_cholmod_copy_sparse', ...
    '../../CHOLMOD/Utility/t_cholmod_copy_triplet', ...
    '../../CHOLMOD/Utility/t_cholmod_cumsum', ...
    '../../CHOLMOD/Utility/t_cholmod_bound', ...
    '../../CHOLMOD/Utility/t_cholmod_defaults', ...
    '../../CHOLMOD/Utility/t_cholmod_dense_nnz', ...
    '../../CHOLMOD/Utility/t_cholmod_dense_to_sparse', ...
    '../../CHOLMOD/Utility/cholmod_divcomplex', ...
    '../../CHOLMOD/Utility/t_cholmod_ensure_dense', ...
    '../../CHOLMOD/Utility/t_cholmod_error', ...
    '../../CHOLMOD/Utility/t_cholmod_eye', ...
    '../../CHOLMOD/Utility/t_cholmod_factor_to_sparse', ...
    '../../CHOLMOD/Utility/t_cholmod_finish', ...
    '../../CHOLMOD/Utility/t_cholmod_free', ...
    '../../CHOLMOD/Utility/t_cholmod_free_dense', ...
    '../../CHOLMOD/Utility/t_cholmod_free_factor', ...
    '../../CHOLMOD/Utility/t_cholmod_free_sparse', ...
    '../../CHOLMOD/Utility/t_cholmod_free_triplet', ...
    '../../CHOLMOD/Utility/t_cholmod_free_work', ...
    '../../CHOLMOD/Utility/cholmod_hypot', ...
    '../../CHOLMOD/Utility/t_cholmod_malloc', ...
    '../../CHOLMOD/Utility/t_cholmod_maxrank', ...
    '../../CHOLMOD/Utility/t_cholmod_mult_size_t', ...
    '../../CHOLMOD/Utility/t_cholmod_nnz', ...
    '../../CHOLMOD/Utility/t_cholmod_ones', ...
    '../../CHOLMOD/Utility/t_cholmod_pack_factor', ...
    '../../CHOLMOD/Utility/t_cholmod_ptranspose', ...
    '../../CHOLMOD/Utility/t_cholmod_reallocate_column', ...
    '../../CHOLMOD/Utility/t_cholmod_reallocate_factor', ...
    '../../CHOLMOD/Utility/t_cholmod_reallocate_sparse', ...
    '../../CHOLMOD/Utility/t_cholmod_reallocate_triplet', ...
    '../../CHOLMOD/Utility/t_cholmod_realloc', ...
    '../../CHOLMOD/Utility/t_cholmod_realloc_multiple', ...
    '../../CHOLMOD/Utility/t_cholmod_bound', ...
    '../../CHOLMOD/Utility/t_cholmod_score_comp', ...
    '../../CHOLMOD/Utility/t_cholmod_set_empty', ...
    '../../CHOLMOD/Utility/t_cholmod_sort', ...
    '../../CHOLMOD/Utility/t_cholmod_sparse_to_dense', ...
    '../../CHOLMOD/Utility/t_cholmod_sparse_to_triplet', ...
    '../../CHOLMOD/Utility/t_cholmod_speye', ...
    '../../CHOLMOD/Utility/t_cholmod_spzeros', ...
    '../../CHOLMOD/Utility/t_cholmod_start', ...
    '../../CHOLMOD/Utility/t_cholmod_transpose', ...
    '../../CHOLMOD/Utility/t_cholmod_transpose_sym', ...
    '../../CHOLMOD/Utility/t_cholmod_transpose_unsym', ...
    '../../CHOLMOD/Utility/t_cholmod_triplet_to_sparse', ...
    '../../CHOLMOD/Utility/t_cholmod_version', ...
    '../../CHOLMOD/Utility/t_cholmod_change_xdtype', ...
    '../../CHOLMOD/Utility/t_cholmod_zeros', ...
    '../../CHOLMOD/Utility/cholmod_mult_uint64_t', ...
    '../../CHOLMOD/Utility/cholmod_memdebug', ...
    '../../CHOLMOD/Check/cholmod_check', ...
    '../../CHOLMOD/Check/cholmod_read', ...
    '../../CHOLMOD/Check/cholmod_write', ...
    '../../CHOLMOD/Cholesky/cholmod_amd', ...
    '../../CHOLMOD/Cholesky/cholmod_analyze', ...
    '../../CHOLMOD/Cholesky/cholmod_colamd', ...
    '../../CHOLMOD/Cholesky/cholmod_etree', ...
    '../../CHOLMOD/Cholesky/cholmod_factorize', ...
    '../../CHOLMOD/Cholesky/cholmod_postorder', ...
    '../../CHOLMOD/Cholesky/cholmod_rcond', ...
    '../../CHOLMOD/Cholesky/cholmod_resymbol', ...
    '../../CHOLMOD/Cholesky/cholmod_rowcolcounts', ...
    '../../CHOLMOD/Cholesky/cholmod_rowfac', ...
    '../../CHOLMOD/Cholesky/cholmod_solve', ...
    '../../CHOLMOD/Cholesky/cholmod_spsolve', ...
    '../../CHOLMOD/MatrixOps/cholmod_drop', ...
    '../../CHOLMOD/MatrixOps/cholmod_horzcat', ...
    '../../CHOLMOD/MatrixOps/cholmod_norm', ...
    '../../CHOLMOD/MatrixOps/cholmod_scale', ...
    '../../CHOLMOD/MatrixOps/cholmod_sdmult', ...
    '../../CHOLMOD/MatrixOps/cholmod_ssmult', ...
    '../../CHOLMOD/MatrixOps/cholmod_submatrix', ...
    '../../CHOLMOD/MatrixOps/cholmod_vertcat', ...
    '../../CHOLMOD/MatrixOps/cholmod_symmetry', ...
    '../../CHOLMOD/Supernodal/cholmod_super_numeric', ...
    '../../CHOLMOD/Supernodal/cholmod_super_solve', ...
    '../../CHOLMOD/Supernodal/cholmod_super_symbolic', ...
    '../../CHOLMOD/Partition/cholmod_ccolamd', ...
    '../../CHOLMOD/Partition/cholmod_csymamd', ...
    '../../CHOLMOD/Partition/cholmod_camd', ...
    '../../CHOLMOD/Partition/cholmod_metis', ...
    '../../CHOLMOD/Partition/cholmod_nesdis', ...
    '../../UMFPACK/Source/umf_analyze', ...
    '../../UMFPACK/Source/umf_apply_order', ...
    '../../UMFPACK/Source/umf_cholmod', ...
    '../../UMFPACK/Source/umf_colamd', ...
    '../../UMFPACK/Source/umf_free', ...
    '../../UMFPACK/Source/umf_fsize', ...
    '../../UMFPACK/Source/umf_is_permutation', ...
    '../../UMFPACK/Source/umf_malloc', ...
    '../../UMFPACK/Source/umf_realloc', ...
    '../../UMFPACK/Source/umf_report_perm', ...
    '../../UMFPACK/Source/umf_singletons', ...
    '../../UMFPACK/Source/umf_assemble', ...
    '../../UMFPACK/Source/umf_assemble', ...
    '../../UMFPACK/Source/umf_blas3_update', ...
    '../../UMFPACK/Source/umf_build_tuples', ...
    '../../UMFPACK/Source/umf_create_element', ...
    '../../UMFPACK/Source/umf_dump', ...
    '../../UMFPACK/Source/umf_extend_front', ...
    '../../UMFPACK/Source/umf_garbage_collection', ...
    '../../UMFPACK/Source/umf_get_memory', ...
    '../../UMFPACK/Source/umf_grow_front', ...
    '../../UMFPACK/Source/umf_init_front', ...
    '../../UMFPACK/Source/umf_kernel', ...
    '../../UMFPACK/Source/umf_kernel_init', ...
    '../../UMFPACK/Source/umf_kernel_wrapup', ...
    '../../UMFPACK/Source/umf_lsolve', ...
    '../../UMFPACK/Source/umf_local_search', ...
    '../../UMFPACK/Source/umf_lsolve', ...
    '../../UMFPACK/Source/umf_ltsolve', ...
    '../../UMFPACK/Source/umf_mem_alloc_element', ...
    '../../UMFPACK/Source/umf_mem_alloc_head_block', ...
    '../../UMFPACK/Source/umf_mem_alloc_tail_block', ...
    '../../UMFPACK/Source/umf_mem_free_tail_block', ...
    '../../UMFPACK/Source/umf_mem_init_memoryspace', ...
    '../../UMFPACK/Source/umf_report_vector', ...
    '../../UMFPACK/Source/umf_row_search', ...
    '../../UMFPACK/Source/umf_scale', ...
    '../../UMFPACK/Source/umf_scale_column', ...
    '../../UMFPACK/Source/umf_set_stats', ...
    '../../UMFPACK/Source/umf_solve', ...
    '../../UMFPACK/Source/umf_start_front', ...
    '../../UMFPACK/Source/umf_store_lu', ...
    '../../UMFPACK/Source/umf_store_lu', ...
    '../../UMFPACK/Source/umf_symbolic_usage', ...
    '../../UMFPACK/Source/umf_transpose', ...
    '../../UMFPACK/Source/umf_triplet', ...
    '../../UMFPACK/Source/umf_triplet', ...
    '../../UMFPACK/Source/umf_triplet', ...
    '../../UMFPACK/Source/umf_triplet', ...
    '../../UMFPACK/Source/umf_tuple_lengths', ...
    '../../UMFPACK/Source/umf_usolve', ...
    '../../UMFPACK/Source/umf_usolve', ...
    '../../UMFPACK/Source/umf_utsolve', ...
    '../../UMFPACK/Source/umf_valid_numeric', ...
    '../../UMFPACK/Source/umf_valid_symbolic', ...
    '../../UMFPACK/Source/umfpack_tictoc', ...
    '../../UMFPACK/Source/umfpack_timer', ...
    '../../UMFPACK/Source/umfpack_col_to_triplet', ...
    '../../UMFPACK/Source/umfpack_defaults', ...
    '../../UMFPACK/Source/umfpack_free_numeric', ...
    '../../UMFPACK/Source/umfpack_free_symbolic', ...
    '../../UMFPACK/Source/umfpack_get_determinant', ...
    '../../UMFPACK/Source/umfpack_get_lunz', ...
    '../../UMFPACK/Source/umfpack_get_numeric', ...
    '../../UMFPACK/Source/umfpack_get_symbolic', ...
    '../../UMFPACK/Source/umfpack_load_numeric', ...
    '../../UMFPACK/Source/umfpack_load_symbolic', ...
    '../../UMFPACK/Source/umfpack_numeric', ...
    '../../UMFPACK/Source/umfpack_qsymbolic', ...
    '../../UMFPACK/Source/umfpack_report_control', ...
    '../../UMFPACK/Source/umfpack_report_info', ...
    '../../UMFPACK/Source/umfpack_report_matrix', ...
    '../../UMFPACK/Source/umfpack_report_numeric', ...
    '../../UMFPACK/Source/umfpack_report_perm', ...
    '../../UMFPACK/Source/umfpack_report_status', ...
    '../../UMFPACK/Source/umfpack_report_symbolic', ...
    '../../UMFPACK/Source/umfpack_report_triplet', ...
    '../../UMFPACK/Source/umfpack_report_vector', ...
    '../../UMFPACK/Source/umfpack_save_numeric', ...
    '../../UMFPACK/Source/umfpack_save_symbolic', ...
    '../../UMFPACK/Source/umfpack_scale', ...
    '../../UMFPACK/Source/umfpack_solve', ...
    '../../UMFPACK/Source/umfpack_symbolic', ...
    '../../UMFPACK/Source/umfpack_transpose', ...
    '../../UMFPACK/Source/umfpack_triplet_to_col', ...
    '../../UMFPACK/Source/umfpack_solve' } ;

paru_src = {
    '../Source/ParU_Factorize', ...
    '../Source/ParU_Analyze', ...
    '../Source/paru_assemble', ...
    '../Source/paru_assemble_row2U', ...
    '../Source/paru_bin_search', ...
    '../Source/ParU_C', ...
    '../Source/paru_create_element', ...
    '../Source/paru_cumsum', ...
    '../Source/paru_dgemm', ...
    '../Source/paru_diag_update', ...
    '../Source/paru_exec_tasks', ...
    '../Source/paru_finalize_perm', ...
    '../Source/ParU_FreeNumeric', ...
    '../Source/ParU_FreeSymbolic', ...
    '../Source/ParU_FreeControl', ...
    '../Source/ParU_InitControl', ...
    '../Source/paru_front', ...
    '../Source/paru_fs_factorize', ...
    '../Source/paru_full_summed', ...
    '../Source/paru_gaxpy', ...
    '../Source/ParU_Get', ...
    '../Source/paru_hash', ...
    '../Source/paru_heap', ...
    '../Source/paru_init_rel', ...
    '../Source/paru_init_rowFronts', ...
    '../Source/paru_intersection', ...
    '../Source/ParU_InvPerm', ...
    '../Source/ParU_LSolve', ...
    '../Source/paru_mem', ...
    '../Source/paru_free_work', ...
    '../Source/paru_memcpy', ...
    '../Source/paru_memset', ...
    '../Source/paru_norms', ...
    '../Source/paru_nthreads', ...
    '../Source/ParU_Perm', ...
    '../Source/paru_pivotal', ...
    '../Source/paru_prior_assemble', ...
    '../Source/ParU_Residual', ...
    '../Source/ParU_Set', ...
    '../Source/ParU_Solve', ...
    '../Source/paru_tasked_dgemm', ...
    '../Source/paru_tasked_dtrsm', ...
    '../Source/paru_dtrsm', ...
    '../Source/paru_tuples', ...
    '../Source/paru_umfpack_info', ...
    '../Source/paru_update_rel_ind', ...
    '../Source/paru_update_rowDeg', ...
    '../Source/ParU_USolve', ...
    '../Source/ParU_Version' } ;

obj_files = ' ' ;
objs = { } ;

% compile each ParU C++ file
for k = 1:length (paru_src)
    src = paru_src {k} ;
    s = sprintf ('mex -c %s %s %s.cpp', flags, include, src) ;
    % fprintf ('%s\n', src) ;
    fprintf ('.') ;
    eval (s) ;
    slash = strfind (src, '/') ;
    slash = slash (end) + 1 ;
    o = src (slash:end) ;
    obj_files = [ obj_files ' ' o '.' obj ] ; %#ok<AGROW>
    objs {end+1} = [o '.' obj] ;
    if (mod (k,60) == 0)
        fprintf ('\n') ;
    end
end
fprintf ('\n') ;

% compile each SuiteSparse C file (SuiteSparse_config, AMD, COLAMD,
% CAMD, CCOLAMD, UMFPACK, CHOLMOD):
for k = 1:length (suitesparse_src)
    src = suitesparse_src {k} ;
    s = sprintf ('mex -c %s %s %s.c', flags, include, src) ;
    % fprintf ('%s\n', src) ;
    fprintf ('.') ;
    eval (s) ;
    slash = strfind (src, '/') ;
    slash = slash (end) + 1 ;
    o = src (slash:end) ;
    obj_files = [ obj_files ' ' o '.' obj ] ; %#ok<AGROW>
    objs {end+1} = [o '.' obj] ;
    if (mod (k,60) == 0)
        fprintf ('\n') ;
    end
end

% compile the paru mexFunction
fprintf (':') ;
s = sprintf ('mex %s -O %s paru.c %s %s', flags, include, obj_files, libs) ;
% fprintf ('%s\n', s) ;
eval (s) ;
fprintf ('\n') ;

% delete the object files
for k = 1:length (objs)
    o = objs {k} ;
    if (length (dir (o)) > 0)
        delete (o) ;
    end
end

% try a quick demo
paru_tiny
paru_demo

end
