#!/bin/sh
#SBATCH --job-name=paru_and_umf
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --partition=bigmem
#SBATCH --mem=2900G
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=80

#   module load GCCcore/13.3.0
#   module load intel/2024a
#   module load imkl/2024.2.0
#   module load intel-compilers/2024.2.0
#   module load GMP/6.3.0
#   module load MPFR/4.2.1
#   module load CMake/3.29.3
#   module load Matlab/R2024a
#   module list

export OMP_MAX_ACTIVE_LEVELS=4
export OMP_NUM_THREADS=24,24
export OMP_DISPLAY_ENV=true
printenv | grep OMP_

/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/rim.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/TSOPF_RS_b39_c30.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/twotone.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/std1_Jac2.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/mac_econ_fwd500.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/std1_Jac3.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/TSOPF_RS_b300_c1.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/lhr71.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/Zd_Jac2.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/av41092.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/Zd_Jac6.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/crashbasis.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/bbmat.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/Zd_Jac3.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/mc2depi.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/TSOPF_RS_b300_c2.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/TSOPF_RS_b678_c1.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/TSOPF_RS_b300_c3.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/Chebyshev4.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/Hamrle3.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/pre2.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/TSOPF_RS_b2052_c1.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/torso1.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/TSOPF_RS_b678_c2.mtx
/home/davis/paru/SuiteSparse/ParU/build/paru_benchmark ~/matrices/TSOPF_RS_b2383.mtx

## too big:
## /scratch/user/davis/SuiteSparse/ParU/build/paru_benchmark /scratch/user/davis/matrices/vas_stokes_4M.mtx
## /scratch/user/davis/SuiteSparse/ParU/build/paru_benchmark /scratch/user/davis/matrices/stokes.mtx

