function cholmod_make
%CHOLMOD_MAKE compiles the CHOLMOD mexFunctions
%
% Example:
%   cholmod_make
%
% CHOLMOD relies on AMD and COLAMD, and optionally CCOLAMD, CAMD, and
% METIS.  You must type the cholmod_make command while in the
% CHOLMOD/MATLAB directory.
%
% See also analyze, bisect, chol2, cholmod2, etree2, lchol, ldlchol,
%   ldlsolve, ldlupdate, metis, spsym, nesdis, septree, resymbol, sdmult,
%   symbfact2, mread, mwrite, ldlrowmod.

 % Copyright 2006-2023, Timothy A. Davis, All Rights Reserved.
 % SPDX-License-Identifier: GPL-2.0+

if verLessThan ('matlab', '9.4')
    error ('MATLAB 9.4 (R2018a) or later is required') ;
end

details = 0 ;       % 1 if details of each command are to be printed

 % -R2018a: interleaved complex is required
flags = '-O -R2018a -silent ' ;

if (ispc)
    % MSVC does not define ssize_t
    flags = [flags ' -DNO_SSIZE_T'] ;
    % disable the SuiteSparse_config timer
    flags = ['-DNTIMER ' flags] ;
end

include = '-I. -I.. -I../../AMD/Include -I../../COLAMD/Include -I../../CCOLAMD/Include -I../../CAMD/Include -I../Include -I../../SuiteSparse_config' ;

if (~ispc)
    % Linux/Unix require these flags for large file support
    include = [include ' -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE'] ;
end

 % Determine if METIS is available.  Set METIS_ROOT for a non-standard
 % installation.  Otherwise the compiler searches its system include paths.
metis_path = getenv ('METIS_ROOT') ;
if (~isempty (metis_path))
    fprintf ('Compiling CHOLMOD with METIS for MATLAB Version %s\n', version) ;
    include = [include ' -I' metis_path '/include'] ;
else
    fprintf ('Compiling CHOLMOD without METIS for MATLAB Version %s\n', version) ;
    include = ['-DNPARTITION ' include] ;
end

 %---------------------------------------------------------------------------
 % BLAS option
 %---------------------------------------------------------------------------

if (ispc)
    % BLAS/LAPACK functions have no underscore on Windows
    flags = [flags ' -DBLAS_NO_UNDERSCORE'] ;
    if (verLessThan ('matlab', '9.5'))
        lapack = 'libmwlapack.lib libmwblas.lib' ;
    else
        lapack = '-lmwlapack -lmwblas' ;
    end
else
    % BLAS/LAPACK functions have an underscore suffix
    flags = [flags ' -DBLAS_UNDERSCORE'] ;
    lapack = '-lmwlapack -lmwblas' ;
end

 % using the 64-bit BLAS
flags = [flags ' -DBLAS64'] ;

if (~(ispc || ismac))
    % for POSIX timing routine
    lapack = [lapack ' -lrt'] ;
end

 %------------------------------------------------------------------------------

config_src = { '../../SuiteSparse_config/SuiteSparse_config' } ;

ordering_src = { ...
    '../../AMD/Source/amd_1', ...
    '../../AMD/Source/amd_2', ...
    '../../AMD/Source/amd_aat', ...
    '../../AMD/Source/amd_control', ...
    '../../AMD/Source/amd_defaults', ...
    '../../AMD/Source/amd_dump', ...
    '../../AMD/Source/amd_info', ...
    '../../AMD/Source/amd_order', ...
    '../../AMD/Source/amd_postorder', ...
    '../../AMD/Source/amd_post_tree', ...
    '../../AMD/Source/amd_preprocess', ...
    '../../AMD/Source/amd_valid', ...
    '../../CAMD/Source/camd_1', ...
    '../../CAMD/Source/camd_2', ...
    '../../CAMD/Source/camd_aat', ...
    '../../CAMD/Source/camd_control', ...
    '../../CAMD/Source/camd_defaults', ...
    '../../CAMD/Source/camd_dump', ...
    '../../CAMD/Source/camd_info', ...
    '../../CAMD/Source/camd_order', ...
    '../../CAMD/Source/camd_postorder', ...
    '../../CAMD/Source/camd_preprocess', ...
    '../../CAMD/Source/camd_valid', ...
    '../../COLAMD/Source/colamd', ...
    '../../CCOLAMD/Source/ccolamd' } ;

sputil2 = { 'sputil2' } ;

cholmod_src = {
    '../Utility/t_cholmod_aat', ...
    '../Utility/t_cholmod_add', ...
    '../Utility/t_cholmod_add_size_t', ...
    '../Utility/t_cholmod_allocate_dense', ...
    '../Utility/cholmod_allocate_factor', ...
    '../Utility/t_cholmod_allocate_sparse', ...
    '../Utility/t_cholmod_allocate_triplet', ...
    '../Utility/cholmod_allocate_work', ...
    '../Utility/t_cholmod_alloc_factor', ...
    '../Utility/t_cholmod_alloc_work', ...
    '../Utility/t_cholmod_band', ...
    '../Utility/t_cholmod_band_nnz', ...
    '../Utility/t_cholmod_malloc', ...
    '../Utility/t_cholmod_change_factor', ...
    '../Utility/t_cholmod_clear_flag', ...
    '../Utility/t_cholmod_copy', ...
    '../Utility/t_cholmod_copy_dense2', ...
    '../Utility/t_cholmod_copy_dense', ...
    '../Utility/t_cholmod_copy_factor', ...
    '../Utility/t_cholmod_copy_sparse', ...
    '../Utility/t_cholmod_copy_triplet', ...
    '../Utility/t_cholmod_cumsum', ...
    '../Utility/t_cholmod_bound', ...
    '../Utility/t_cholmod_defaults', ...
    '../Utility/t_cholmod_dense_nnz', ...
    '../Utility/t_cholmod_dense_to_sparse', ...
    '../Utility/cholmod_divcomplex', ...
    '../Utility/t_cholmod_ensure_dense', ...
    '../Utility/t_cholmod_error', ...
    '../Utility/t_cholmod_eye', ...
    '../Utility/t_cholmod_factor_to_sparse', ...
    '../Utility/t_cholmod_finish', ...
    '../Utility/t_cholmod_free', ...
    '../Utility/t_cholmod_free_dense', ...
    '../Utility/t_cholmod_free_factor', ...
    '../Utility/t_cholmod_free_sparse', ...
    '../Utility/t_cholmod_free_triplet', ...
    '../Utility/t_cholmod_free_work', ...
    '../Utility/cholmod_hypot', ...
    '../Utility/t_cholmod_malloc', ...
    '../Utility/t_cholmod_maxrank', ...
    '../Utility/t_cholmod_mult_size_t', ...
    '../Utility/t_cholmod_nnz', ...
    '../Utility/t_cholmod_ones', ...
    '../Utility/t_cholmod_pack_factor', ...
    '../Utility/t_cholmod_ptranspose', ...
    '../Utility/t_cholmod_reallocate_column', ...
    '../Utility/t_cholmod_reallocate_factor', ...
    '../Utility/t_cholmod_reallocate_sparse', ...
    '../Utility/t_cholmod_reallocate_triplet', ...
    '../Utility/t_cholmod_realloc', ...
    '../Utility/t_cholmod_realloc_multiple', ...
    '../Utility/t_cholmod_bound', ...
    '../Utility/t_cholmod_score_comp', ...
    '../Utility/t_cholmod_set_empty', ...
    '../Utility/t_cholmod_sort', ...
    '../Utility/t_cholmod_sparse_to_dense', ...
    '../Utility/t_cholmod_sparse_to_triplet', ...
    '../Utility/t_cholmod_speye', ...
    '../Utility/t_cholmod_spzeros', ...
    '../Utility/t_cholmod_start', ...
    '../Utility/t_cholmod_transpose', ...
    '../Utility/t_cholmod_transpose_sym', ...
    '../Utility/t_cholmod_transpose_unsym', ...
    '../Utility/t_cholmod_triplet_to_sparse', ...
    '../Utility/t_cholmod_version', ...
    '../Utility/t_cholmod_change_xdtype', ...
    '../Utility/t_cholmod_zeros', ...
    '../Utility/cholmod_mult_uint64_t', ...
    '../Utility/cholmod_memdebug', ...
    '../Check/cholmod_check', ...
    '../Check/cholmod_read', ...
    '../Check/cholmod_write', ...
    '../Cholesky/cholmod_amd', ...
    '../Cholesky/cholmod_analyze', ...
    '../Cholesky/cholmod_colamd', ...
    '../Cholesky/cholmod_etree', ...
    '../Cholesky/cholmod_factorize', ...
    '../Cholesky/cholmod_postorder', ...
    '../Cholesky/cholmod_rcond', ...
    '../Cholesky/cholmod_resymbol', ...
    '../Cholesky/cholmod_rowcolcounts', ...
    '../Cholesky/cholmod_rowfac', ...
    '../Cholesky/cholmod_solve', ...
    '../Cholesky/cholmod_spsolve', ...
    '../MatrixOps/cholmod_drop', ...
    '../MatrixOps/cholmod_horzcat', ...
    '../MatrixOps/cholmod_norm', ...
    '../MatrixOps/cholmod_scale', ...
    '../MatrixOps/cholmod_sdmult', ...
    '../MatrixOps/cholmod_ssmult', ...
    '../MatrixOps/cholmod_submatrix', ...
    '../MatrixOps/cholmod_vertcat', ...
    '../MatrixOps/cholmod_symmetry', ...
    '../Modify/cholmod_rowadd', ...
    '../Modify/cholmod_rowdel', ...
    '../Modify/cholmod_updown', ...
    '../Supernodal/cholmod_super_numeric', ...
    '../Supernodal/cholmod_super_solve', ...
    '../Supernodal/cholmod_super_symbolic', ...
    '../Partition/cholmod_ccolamd', ...
    '../Partition/cholmod_csymamd', ...
    '../Partition/cholmod_camd', ...
    '../Partition/cholmod_metis', ...
    '../Partition/cholmod_nesdis' } ;

cholmod_mex_src = { ...
    'analyze', ...
    'bisect', ...
    'chol2', ...
    'cholmod2', ...
    'etree2', ...
    'lchol', ...
    'ldlchol', ...
    'ldlsolve', ...
    'ldlupdate', ...
    'ldlrowmod', ...
    'metis', ...
    'spsym', ...
    'nesdis', ...
    'septree', ...
    'resymbol', ...
    'sdmult', ...
    'symbfact2', ...
    'mread', ...
    'mwrite', ...
    'lxbpattern', 'lsubsolve' } ;   % <=== these 2 are just for testing

if (ispc)
    obj_extension = '.obj' ;
else
    obj_extension = '.o' ;
end

 % compile each library source file
obj = '' ;

source = [sputil2 ordering_src config_src cholmod_src ] ;

kk = 0 ;

for f = source
    ff = f {1} ;
    slash = strfind (ff, '/') ;
    if (isempty (slash))
        slash = 1 ;
    else
        slash = slash (end) + 1 ;
    end
    o = ff (slash:end) ;
    % fprintf ('%s\n', o) ;
    o = [o obj_extension] ;                                                 %#ok
    obj = [obj  ' ' o] ;                                                    %#ok
    s = sprintf ('mex %s %s -c %s.c', flags, include, ff) ;
    kk = do_cmd (s, kk, details, '.') ;
end

 % compile each mexFunction
for f = cholmod_mex_src
    s = sprintf ('mex %s %s %s.c', flags, include, f{1}) ;
    s = [s obj ' ' lapack] ;                                                %#ok
    kk = do_cmd (s, kk, details, ':') ;
end

 % clean up
s = ['delete ' obj] ;
do_cmd (s, kk, details, '.') ;
fprintf ('\nCHOLMOD successfully compiled\n') ;

 %-----------------------------------------------------------------------------
function kk = do_cmd (s, kk, details, progress)
 %DO_CMD: evaluate a command, and either print it or print a "."
if (details)
    fprintf ('%s\n', s) ;
else
    if (mod (kk, 60) == 0)
        fprintf ('\n') ;
    end
    kk = kk + 1 ;
    fprintf (progress) ;
end
eval (s) ;

