function err = testall (pr)
%TESTALL run all piro_band tests.
% You must first compile PIRO_BAND with piro_band_make.
%
% Example
%
%   testall
%   testall (1) ;       % print details
%
% See also piro_band_make.

% For complete testing, the spok function is used to verify the sparse matrices
% generated by the PIRO_BAND function.

% Copyright 2012, Sivasankaran Rajamanickam, Timothy A. Davis
% http://www.cise.ufl.edu/research/sparse

if (nargin < 1)
    pr = 0 ;
end
fprintf ('Please wait ...\n') ;
here = pwd ;
cd ..
piro_band_make
cd (here) ;
piro_band_test_make
fprintf ('Testing ') ;
err = 0 ;
err = max (err, test_piro_band_special (pr)) ;
err = max (err, test_piro_band_svd (pr)) ;
fprintf ('\nAll tests passed.  max error: %g\n', err) ;
